title: ldequadra
description: Engenharia Eletrotécnica
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ldequadra.github.io/

# User settings
username: Luiz Claudio de Quadra
user_description: Busco estudar o que posso para aprender o que preciso.
user_title: Engenharia Eletrotécnica
email: luliquadra21@gmail.com
twitter_username: ldequadra
github_username:  ldequadra
gplus_username:  ldequadra

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
