# Site settings
title: Luiz Claudio de Quadra
description: keep learning
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://ldequadra.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ldequadra
user_description: Busco estudar o que posso afim de aprender o que preciso.
user_title: Engenharia Eletrotécnica
email: luliquadra21@gmail.com
twitter_username: ldequadra
github_username:  ldequadra

exclude: ['package.json', 'src' , 'node_modules']
