# Site settings
title: Luiz Claudio de Quadra
description: Electrical Engineering
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://ldequadra.github.io/

# User settings
username: ldequadra
user_description: "Always aware on the growing technological advance and constant globalization, I'm a competitive and autonomous professional, with conscious decision making, aiming to the maximum the safety at the organizational environment."
user_title: Electrical Engineering
email: luliquadra21@gmail.com
twitter_username: ldequadra
github_username:  ldequadra
gplus_username:  ldequadra

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']